
package uk.ac.ebi.fgpt.sampletab.utils.europmc.ws;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "WSCitationImplService", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", wsdlLocation = "http://www.ebi.ac.uk/webservices/citexplore/v3.0.1/service?wsdl")
public class WSCitationImplService
    extends Service
{

    private final static URL WSCITATIONIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.WSCitationImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.WSCitationImplService.class.getResource(".");
            url = new URL(baseUrl, "http://www.ebi.ac.uk/webservices/citexplore/v3.0.1/service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://www.ebi.ac.uk/webservices/citexplore/v3.0.1/service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSCITATIONIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WSCitationImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSCitationImplService() {
        super(WSCITATIONIMPLSERVICE_WSDL_LOCATION, new QName("http://webservice.cdb.ebi.ac.uk/", "WSCitationImplService"));
    }

    /**
     * 
     * @return
     *     returns WSCitationImpl
     */
    @WebEndpoint(name = "WSCitationImplPort")
    public WSCitationImpl getWSCitationImplPort() {
        return super.getPort(new QName("http://webservice.cdb.ebi.ac.uk/", "WSCitationImplPort"), WSCitationImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSCitationImpl
     */
    @WebEndpoint(name = "WSCitationImplPort")
    public WSCitationImpl getWSCitationImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.cdb.ebi.ac.uk/", "WSCitationImplPort"), WSCitationImpl.class, features);
    }

}
