
package uk.ac.ebi.fgpt.sampletab.utils.europmc.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "WSCitationImpl", targetNamespace = "http://webservice.cdb.ebi.ac.uk/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSCitationImpl {


    /**
     * 
     * @param queryString
     * @param email
     * @param synonym
     * @param resultType
     * @param offSet
     * @param dataSet
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchPublications", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.SearchPublications")
    @javax.xml.ws.ResponseWrapper(localName = "searchPublicationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.SearchPublicationsResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper searchPublications(
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "dataSet", targetNamespace = "")
        String dataSet,
        @WebParam(name = "resultType", targetNamespace = "")
        String resultType,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "synonym", targetNamespace = "")
        Boolean synonym,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param queryString
     * @param profileType
     * @param email
     * @param synonym
     * @param dataSet
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "profilePublications", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ProfilePublications")
    @javax.xml.ws.ResponseWrapper(localName = "profilePublicationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ProfilePublicationsResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper profilePublications(
        @WebParam(name = "queryString", targetNamespace = "")
        String queryString,
        @WebParam(name = "dataSet", targetNamespace = "")
        String dataSet,
        @WebParam(name = "profileType", targetNamespace = "")
        String profileType,
        @WebParam(name = "synonym", targetNamespace = "")
        Boolean synonym,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCitations", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetCitations")
    @javax.xml.ws.ResponseWrapper(localName = "getCitationsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetCitationsResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper getCitations(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getReferences", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetReferences")
    @javax.xml.ws.ResponseWrapper(localName = "getReferencesResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetReferencesResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper getReferences(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param semanticType
     * @param source
     * @param email
     * @param offSet
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTextMinedTerms", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetTextMinedTerms")
    @javax.xml.ws.ResponseWrapper(localName = "getTextMinedTermsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetTextMinedTermsResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper getTextMinedTerms(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "semanticType", targetNamespace = "")
        String semanticType,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @param offSet
     * @param database
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDatabaseLinks", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetDatabaseLinks")
    @javax.xml.ws.ResponseWrapper(localName = "getDatabaseLinksResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetDatabaseLinksResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper getDatabaseLinks(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "database", targetNamespace = "")
        String database,
        @WebParam(name = "offSet", targetNamespace = "")
        Integer offSet,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.Result
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSupplementaryFiles", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetSupplementaryFiles")
    @javax.xml.ws.ResponseWrapper(localName = "getSupplementaryFilesResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetSupplementaryFilesResponse")
    public Result getSupplementaryFiles(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param id
     * @param source
     * @param email
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.Result
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFulltextXML", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetFulltextXML")
    @javax.xml.ws.ResponseWrapper(localName = "getFulltextXMLResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.GetFulltextXMLResponse")
    public Result getFulltextXML(
        @WebParam(name = "id", targetNamespace = "")
        String id,
        @WebParam(name = "source", targetNamespace = "")
        String source,
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

    /**
     * 
     * @param email
     * @return
     *     returns uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper
     * @throws QueryException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listSearchFields", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ListSearchFields")
    @javax.xml.ws.ResponseWrapper(localName = "listSearchFieldsResponse", targetNamespace = "http://webservice.cdb.ebi.ac.uk/", className = "uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ListSearchFieldsResponse")
    public uk.ac.ebi.fgpt.sampletab.utils.europmc.ws.ResponseWrapper listSearchFields(
        @WebParam(name = "email", targetNamespace = "")
        String email)
        throws QueryException_Exception
    ;

}
